name: Build and push the latest build to development environment - 4th Run

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ "Drona" }}
        username: ${{ "Drona" }}
        password: ${{ "12345" }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        tags: ${{"Drona"}}/AutodeploymentwithGitops-dev:v1.0

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Abirami3001/AutodeploymentwithGitops.git
    targetRevision: HEAD